---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovirt-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ovirt-csi-driver-operator
  template:
    metadata:
      labels:
        name: ovirt-csi-driver-operator
    spec:
      serviceAccountName: ovirt-csi-driver-operator
      priorityClassName: system-cluster-critical
      containers:
        - name: ovirt-csi-driver-operator
          image: quay.io/ovirt/csi-driver-operator
          imagePullPolicy: IfNotPresent
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
          args:
            - start
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ovirt-csi-driver-operator"
            - name: RELATED_IMAGE_DRIVER
              value: quay.io/ovirt/csi-driver:latest
            - name: RELATED_IMAGE_PROVISIONER
              value: quay.io/openshift/origin-csi-external-provisioner:latest
            - name: RELATED_IMAGE_ATTACHER
              value: quay.io/openshift/origin-csi-external-attacher:latest
            - name: RELATED_IMAGE_RESIZER
              value: quay.io/openshift/origin-csi-external-resizer:latest
            - name: RELATED_IMAGE_SNAPSHOTTER
              value: quay.io/openshift/origin-csi-external-snapshotter:latest
            - name: RELATED_IMAGE_NODE_DRIVER_REGISTRAR
              value: quay.io/openshift/origin-csi-node-driver-registrar:latest
            - name: RELATED_IMAGE_LIVENESS_PROBE
              value: quay.io/openshift/origin-csi-livenessprobe:latest
