apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ovirt-csi-driver-controller-pdb
  namespace: openshift-cluster-csi-drivers
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: ovirt-csi-driver-controller
