apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi
parameters:
  type: gp2
  encrypted: "true"
provisioner: csi.ovirt.org
reclaimPolicy: "Delete"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
